"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#2B3448)\
$os\
$username\
$hostname\
[](bg:#2e3b5b fg:#2B3448)\
$directory\
[](fg:#2e3b5b bg:#556c75)\
$git_branch\
$git_status\
[](fg:#556c75 bg:#dab281)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$swift\
[](fg:#dab281 bg:#b36c4c)\
$docker_context\
[](fg:#b36c4c bg:#833535)\
$shell\
$time\
[ ](fg:#833535)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#2B3448 fg:#d3d7cf"
style_root = "bg:#2B3448 fg:#d3d7cf"
format = '[$user]($style)'
disabled = false

[hostname]
ssh_symbol = " 󰌘"
ssh_only = false
style = "bg:#2B3448 fg:#d3d7cf"
format = "[@$hostname$ssh_symbol ]($style)"

[os]
style = "bg:#2B3448 fg:#d3d7cf"
disabled = false # Disabled by default

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[directory]
style = "bg:#2e3b5b fg:#d3d7cf"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#dab281 fg:#2B3448"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#dab281 fg:#2B3448"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#b36c4c fg:#2B3448"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#dab281 fg:#2B3448"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#dab281 fg:#2B3448"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#556c75 fg:#d3d7cf"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#556c75 fg:#d3d7cf"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#dab281 fg:#2B3448"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#dab281 fg:#2B3448"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#dab281 fg:#2B3448"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#dab281 fg:#2B3448"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#dab281 fg:#2B3448"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#dab281 fg:#2B3448"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#dab281 fg:#2B3448"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#dab281 fg:#2B3448"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#dab281 fg:#2B3448"
format = '[ $symbol ($version) ]($style)'

[swift]
symbol = "󰛥 "
style = "bg:#dab281 fg:#2B3448"
format = '[ $symbol ($version) ]($style)'

[shell]
disabled = false
fish_indicator = " "
bash_indicator = " "
zsh_indicator = "󰰶 "
style = "bg:#833535 fg:#d3d7cf"
format = '[ $indicator ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#833535 fg:#d3d7cf"
format = '[$time ]($style)'
